version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Fulmine123?
      MYSQL_PASSWORD: Fulmine123?
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8091:80   # Accedi a Nextcloud via http://IP_DEL_SERVER:8080
    environment:
      MYSQL_PASSWORD: Fulmine123?
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud_data:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro

volumes:
  db_data:
  nextcloud_data: